---
# tasks file for add_dir_users_timezone
- name: Creates directory
  file:
    path: /opt/logs
    state: directory

- name: Set timezone to Europe/Kaliningrad
  shell: timedatectl set-timezone Europe/Kaliningrad

- name: Add user to remote hosts
  user: name=sasha groups=sudo shell=/bin/bash

- name: Add SSH keys to remote hosts
  authorized_key: user=sasha key="{{ lookup('file', "/home/ubuntu/.ssh/id_rsa.pub") }}"


- name: ensure private key and public one are present
  copy:
    src: /home/ubuntu/.ssh/id_rsa.pub
    dest: "/home/sasha/.ssh/authorized_keys"
    mode: 0600

- name: Add user "sasha" to sudo
  lineinfile:
    path: /etc/sudoers.d/sasha
    line: 'sasha ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
